@startuml testuml
' alt+d for preview
title Foilboard main contoller
start
partition initialize {
    partition Battery {
        :Connect with bms;
        :Comfirm battery;
        :get battery data;
        
    }
    partition Controller {
        :Connect with bluetooth contoller;
        :display battery procentage;
    }
}
partition Mainprogram {
    while (main loop) is (true)
        /'ToAsk: how to display ISR?'/
        floating note right
            getData() with ISR,
            Not with polling
        end note
        if (is button pushed) then (yes)
            :Propeller is rotating;
        else (no)
        endif
    endwhile (exit loop)
    :shutdown safe;
}
stop
@enduml